version: "3"

services:
  taxi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi-app
#    links:
#      - database
#    environment:
#      - ORG_NEO4J_URI=bolt://database:7687
#      - NEO4J_PASSWORD=secret
#    depends_on:
#      database:
#        condition: service_healthy
    ports:
      - "8081:8081"
    restart: on-failure

#  database:
#    image: neo4j:4.0.1
#    environment:
#      - NEO4J_AUTH=neo4j/secret
#    ports:
#      - "7474:7474"
#      - "7687:7687"
#    restart: on-failure
#    healthcheck:
#      test: cypher-shell --username neo4j --password secret 'MATCH (n) RETURN COUNT(n);' # Checks if neo4j server is up and running
#      interval: 10s
#      timeout: 10s
#      retries: 5